### ISSUE TITLE
[231028] 몬스터 사망 이후에 HP바만 남아있는 현상

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#200]
몬스터 HP 0 도달 후 사망상태가 되면 몬스터가 사라지고 HP바만 몇 초 더 남아있음

플레이에 지장은 없지만 UI개선 요망

![FUT_1027_003](https://github.com/Team-Futurity/Futurity/assets/125863403/b13d435a-90a1-42e0-8e06-4495e87d0329)

**Comment by rbase0218** [comment]
몬스터에 삭제 타이밍과 동일하므로, 해당 건은 몬스터쪽에서 별도의 처리가 필요로 합니다.
