### ISSUE TITLE
[231028] 부품 상자 상호작용 안되는 현상

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#201]
부품 상자와 상호작용이 되지 않음.
부품 시스템 사용 불가
![FUT_1027_004](https://github.com/Team-Futurity/Futurity/assets/125863403/405b616c-8b19-4604-a3ac-8c2bd4280103)

**Comment by rbase0218** [comment]
아직 미개발 건으로 이전 레거시 코드 사용중으로 알고 있습니다.

**Comment by rbase0218** [comment]
개발 완료하였으므로, 이슈 닫겠습니다.
