### ISSUE TITLE
[231028] 1스테이지에서 2스테이지로 이동 직전, 대시이동 시 벽 통과되는 현상

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#203]
1스테이지 마지막 몬스터 사망 후, 다음 스테이지로 이동하는 벽과 조금 떨어져서 대시를 사용하면
스트립트 진행 전에 상호작용 없이 벽을 통과하여 이동되는 현상

https://github.com/Team-Futurity/Futurity/assets/125863403/18a10b53-4c06-4020-a50f-ec5655cb7015

**Comment by Hyoung-Seok** [comment]
수정 완료
