### ISSUE TITLE
[231029] 플레이어 캐릭터 달리기 모션의 부자연스러움

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#207]
플레이어 캐릭터가 한 방향으로 계속 달려갈 경우 중간에 모션이 잠시 멈춘 채로 이동하는 시간이 존재함

https://github.com/Team-Futurity/Futurity/assets/125863403/fc7dae9e-de2a-43e2-b5e2-f7f6df54d2a4

**Comment by Budy123** [comment]
Move 애니가 바뀌고 수정이 들어가기 전에 뽑힌 빌드인가봅니다! 지금은 수정 되었고, 다음 빌드에서 수정된 것 확인되면 Close 하겠습니다~

**Comment by Budy123** [comment]
빌드에선 수정돼서 Close 합니다!
