### ISSUE TITLE
[231029] (2구역)콜라이더 미설치 스테이지에 막힘 구역 있음

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#209]
콜라이더 미설치 스테이지에서 플레이어 이동 불가 구역이 존재함
2구역 스테이지 - 위치 아래 첨부자료 확인 필요

https://github.com/Team-Futurity/Futurity/assets/125863403/6179017f-7410-4084-8d4d-e4e419380d69

**Comment by Hyoung-Seok** [comment]
수정 완료
