### ISSUE TITLE
[231029] 스킵 사용 후 화면이 전환되지 않는 현상

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#210]
스테이지 스킵버튼 F7 버튼 사용 후 불특정 확률로 버그 발생
다음 스테이지로의 전환이 되지 않음
로딩창 혹은 다음 스테이지 시작 지점에서 진행되지 않음

위와 같은 상황에서 F7 버튼을 누르면 기존 스킵 버튼을 사용했을 때와 같이 화면이 검게 변하지만 버튼 사용 전 화면과 동일한 화면이 출력됨. 

https://github.com/Team-Futurity/Futurity/assets/125863403/4298d6e0-2b95-4fdd-ba93-0daa46d1a9ad

https://github.com/Team-Futurity/Futurity/assets/125863403/ed387195-6b70-4a42-b061-252218ca7b19

**Comment by Hyoung-Seok** [comment]
해당 기능은 디버그를 위한 기능이므로 따로 수정하지는 않겠습니다. 만약 스테이지를 클리어 후 해당 버그가 발생한다면 그 때 다시 자세히 적어주시면 감사하겠습니다.
