### ISSUE TITLE
[231029] 게임오버 씬 옵션 선택 이후 게임이 진행되지 않는 현상

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#212]
플레이어 사망 이후 게임오버 화면에서 메인메뉴 / 다시시작 선택 이후에 게임이 진행되지 않는 현상

첨부자료는 다시시작 선택 시의 현상. 메인메뉴를 선택해도 동일한 현상이 발생

https://github.com/Team-Futurity/Futurity/assets/125863403/a45831e8-9907-468b-8f5e-6627843223bf

**Comment by rbase0218** [comment]
수정했습니다.
