### ISSUE TITLE
[231029] 플레이어 사망 이후 화면이 확대 되었을 때, 몬스터 HP바 UI가 이탈하는 현상

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#213]
플레이어가 HP0에 도달하여 사망상태가 되었을 경우, 화면이 확대 됨.
화면이 확대되어도 몬스터 HP바는 원래 형태, 위치가 유지되어 있어야 할 장소에서 UI가 이탈 됨

![FUT_1029_009](https://github.com/Team-Futurity/Futurity/assets/125863403/983aecc2-ed99-41a6-bf89-faea6c0c9af8)

**Comment by Hyoung-Seok** [comment]
수정 완료
