### ISSUE TITLE
[231029] 튜토 컷씬 화질 문제 / 연출 문제

### ISSUE THREAD

**Issue by MinjuGwak** [Team-Futurity/Futurity#215]
튜토리얼 2번째 씬의 화질이 이상합니다!

![image](https://github.com/Team-Futurity/Futurity/assets/89762274/1b4530ce-87ed-4b1d-b8ef-0df67ee4c7b0)

현재 이 컷씬의 빛나는 연출도 이상합니다. 애니메이션 수정이 필요할 것 같습니다!
![image](https://github.com/Team-Futurity/Futurity/assets/89762274/80b8305b-7b54-4c8b-8bec-7e74bd07e4f3)

이전 연출처럼 화아악 빛나는 연출이 있으면 좋겠습니다. 화면이 하얗게 번진 직후 쓰러지는 장면이 나와야 좀 더 자연스러울 것 같습니다.
![image](https://github.com/Team-Futurity/Futurity/assets/89762274/d48d3e7e-7d48-4f54-83da-88a1e677ef67)

**Comment by PZuHi** [comment]
1. 출력 시 이미지 사이즈 1.0->3.0으로 변경하여 화질 개선 완료. 
2. 화면이 하얗게 빛난 후 컷씬 넘어가도록 애니 수정 완료.
