### ISSUE TITLE
[231029] 엑티브 스킬 이슈

### ISSUE THREAD

**Issue by silvereun36** [Team-Futurity/Futurity#217]
엑티브 스킬을 사용하고, 마지막 포즈를 할 때, 이동키를 누르면 마지막 포즈를 한채로 움직입니다.
![엑티브 문제](https://github.com/Team-Futurity/Futurity/assets/64335656/8bb79e31-9a40-4a60-b395-23429c89c905)

**Comment by Budy123** [comment]
해결했습니다.
