### ISSUE TITLE
[20231029]로딩 창 이미지 내 오타(카트로 연구소)

### ISSUE THREAD

**Issue by PZuHi** [Team-Futurity/Futurity#218]
![image](https://github.com/Team-Futurity/Futurity/assets/100755257/71e2421b-1ba6-4b4c-ba96-623d07eb0a02)
케트로 연구소가 카트로 연구소로 적혀있습니다.

**Comment by KIMDODODODO** [comment]
제가 텍스트 작업을 하며 오타가 난 것 같습니다. 
현재 임시로 프리팹을 수정해 뒀으며 후에 로딩 화면 기능이 들어가면 정상적으로 나올 것 같습니다.
