### ISSUE TITLE
[231030] UI HP 효과 누락

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#229]
게임 내 모든 HP 바에 HP 연출(롤 HP) 누락됐습니다.
Assets\03Graphics\UI\Battle\New_Battle에 hp_fill2 네임 리소스 모두 적용 요청 바랍니다.

**Comment by rbase0218** [comment]
작업 진행 후순위로 아직 미진행된 작업입니다.

**Comment by KIMDODODODO** [comment]
확인했습니다.
