### ISSUE TITLE
[231030] Player info 내 액티브 아이콘 연출 누락

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#230]
Player info 내 액티브 아이콘 연출 누락
: 콤보 게이지 100 달성 시 -> 액티브 UI 이펙트 -> 액티브 리소스 F_ui_active_icon_battle_xxx_0에서  F_ui_active_icon_battle_xxx_100 연출 누락

**Comment by rbase0218** [comment]
파티클 추가되었으므로, 이슈 닫겠습니다.
