### ISSUE TITLE
[231030] 설정화면 UI (옵션) 저장 후 뒤로가기 리소스 누락

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#231]
설정화면 내 [ 저장 후 뒤로 가기 ]  리소스 누락됐습니다. 적용 부탁드립니다. 
F_ui_setting_button_normal
F_ui_setting_button_pressed

**Comment by rbase0218** [comment]
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/57909672-fb14-40b3-a554-a3a19174634b)

해당 이미지가 아닌가요?

**Comment by KIMDODODODO** [comment]
해당 이미지 맞습니다. 빌드 파일 내에서는 X 이미지로 보이고있습니다.
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/df10c706-d6e8-43b3-b549-ebab0521d801)

**Comment by rbase0218** [comment]
수정된 이슈로 넘어가겠습니다.
