### ISSUE TITLE
[231030] Normal Dialog 수정 요청

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#232]
* 송사리 일러스트 -> 송사리 2D 애니메이션으로 변경 요청 
* 동일하게 미래와 보스도 일러스트 -> 2D 애니메이션으로 변경 요청 (작업 기한 상 무리다 싶으시면 말씀해 주세요.)
=> 둘 다 Normal Dialog Window에 배치 해뒀습니다.

* 스탠딩 스크립트 뜨는 연출처럼 normal dialog도 동일한 연출 요청

**Comment by rbase0218** [comment]
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/58289d71-e740-49e1-8be8-68aac5438144)

지금 나와있는 리소스로 배치하면 어긋나게 됩니다. 리소스 배치 확인 부탁드립니다.

**Comment by rbase0218** [comment]
추가로 각각 애니메이션 파일 이름 알려주시면 감사하겠습니다.

**Comment by KIMDODODODO** [comment]
배치 다시 잡아 업로드했습니다. 
계속 위치가 어긋날 경우 Normal Dialog Window에 애니메이션 배치해주시면 제가 그때 한 번 더 배치를 잡는 걸로 하겠습니다.

애니메이션 파일 이름은 해당 작업자에게 여쭤보고있습니다. 후에 다시 답변 드리도록 하겠습니다.

**Comment by KIMDODODODO** [comment]
03 Graphics-2DAnimationClips-boss/npc/pc 내 boss_standing / songsari_standing / mirae_standing 입니다. 확인 부탁드립니다.
