### ISSUE TITLE
[231030] 엘리트, 쫄몹 HP 크기 스케일 조정에 대한 질문

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#233]
엘리트 몬스터 HP와 쫄몹 HP 스케일 변경이 필요합니다.
(사유 : 엘리트와 일반 몬스터의 HP 크기가 동일해 구분이 안감, 쫄몹 HP 너무 작음)

엘리트 몬스터 프리팹 위치, 쫄몹 HP 프리팹 위치 가르쳐주시면 직접 수정하겠습니다.
어디에 있나요.....? ;-;

**Comment by rbase0218** [comment]
02Prefab -> 05UI -> Enemy

위 링크에 존재합니다.

**Comment by KIMDODODODO** [comment]
위 프리팹 하나로 엘리트, 쫄몹, 일반 몬스터 HP 돌려쓰나요? 
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/17bb44eb-c0b5-4f28-bc7a-f756385ae5f0)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/9a977e4e-ef8d-4454-9879-e55f795d5e99)

**Comment by rbase0218** [comment]
BH/Feature/UI 브랜치 확인 부탁드립니다. 기존에는 Prefab 데이터가 이상하게 잡혀 있어서 제 UI 브랜치가 UI는 가장 최신입니다.
