### ISSUE TITLE
[231030] 변경된 콤보 숫자 리소스 누락 및 콤보 변경 요청

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#234]
* 콤보 숫자(Combo Number) 기존 리소스로 나옵니다.
Assets\03Graphics\UI\Combo_Number\New 폴더에 있는 리소스로 변경 부탁드립니다.
(Addressable 바꾸고 Critical Combo Group에 Number Sprite Images만 바꾸면 되나요? 제가 할 수 있으면 하겠습니다..)

* 콤보 애니메이션 기존 작업하셨던 것 그대로 적용 부탁드립니다.

**Comment by rbase0218** [comment]
다음부터는 New 폴더 생성해서 만드시지 마시고, 기존 파일에 그대로 덮어쓰기 부탁드립니다. 또한, 리소스 수정이나 위치 변경 시 반드시 UI 카카오톡을 통해서 말씀해주세요.
