### ISSUE TITLE
[231030] 로딩화면 텍스트 변경 누락

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#235]
로딩화면 텍스트 변경이 누락되었습니다.

* 로딩화면 뉴스 텍스트 로딩화면 나올 때 마다 랜덤하게 변경 요청 (스크립트 문서 참고)
* 로딩화면 날짜, 온도 로딩화면 나올 때 마다 해당 맵에 맞게 변경 요청 (스크립트 문서 참고)
* 로딩화면 CCTV내 사진에 있는 날짜와 시간도 해당 맵에 맞게 변경 요청 (스크립트 문서 참고)

**Comment by rbase0218** [comment]
기능 개발 종료했습니다.

![image](https://github.com/Team-Futurity/Futurity/assets/44202628/dbf99690-b96e-44ba-8252-553bfbec5ee1)

위 사진에 해당하는 파일을 생성하시고, 파일에 있는 데이터를 채워주신 다음에 아래의 사진처럼 등록해주시면 완료가 됩니다.
해당하는 텍스트나 데이터를 채우셔서 아래의 사진처럼 등록해주시기를 바랍니다.

![image](https://github.com/Team-Futurity/Futurity/assets/44202628/3fc82c04-1f3f-47da-99a7-5712a6827ce1)

위 사진에 보이는 스크립트 파일은 Scene을 로딩하는 모든 UI Button에 붙어있습니다. 이외 움직이는 경우, 다른 작업자에게 요청해서 Interface의 확장이 필요로 합니다.

참고로 Default 이미지에 대해서 처리가 필요할 것 같습니다. ( Title -> Tutorial 이동 및 InGame -> Title 이동 시 보이는 데이터 )

**Comment by rbase0218** [comment]
기능 개발 완료 건으로 이슈 닫겠습니다.
