### ISSUE TITLE
[231030] 컷씬 텍스트 시간 연출 및 수정

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#236]
* 2100년 06월 12일/ 대한민국 태엽시/ 10년전.. 텍스트만 한 글자 씩 나오게 수정
[https://youtu.be/8nQVphJnmN4?si=Par3kR-1hEJsi8Gw&t=4](url) : 참고영상

* 컷씬 텍스트 보여지는 시간 조금 더 길게 (2100년 06월 12일~ 10년 전..)

** 누구 담당이신지 몰라 둘 다 체크했습니다.. 담당이신 분만 답장해주세요..

**Comment by Hyoung-Seok** [comment]
수정 완료
