### ISSUE TITLE
[231105] 1스테이지 실외기 그래픽 깨짐

### ISSUE THREAD

**Issue by 3unju** [Team-Futurity/Futurity#249]
**STEP**

1. 1 스테이지 진입 후 실외기 위치까지 이동

**실행결과**
일부 실외기의 그래픽이 깨져보이는 것을 확인 
(위치는 참고자료 확인 필요)

**재현율**

100%

 
**특이사항**

https://github.com/Team-Futurity/Futurity/assets/125863403/dfb77f7d-ba6b-4589-96f6-aaa8d29f2db5
영상 좌상단 확인

**Comment by Budy123** [comment]
해결됐습니다!
