### ISSUE TITLE
[231106] 챕터 2-2 문 애니메이션 구동

### ISSUE THREAD

**Issue by PZuHi** [Team-Futurity/Futurity#263]
![image](https://github.com/Team-Futurity/Futurity/assets/100755257/4fba2eaf-6e40-4fb8-a272-ce85a97f8ed1)

챕터 2-2 스테이지에 스테이지 시작할 때 바로 앞에 문을 다른 문처럼 열고 닫게 만들어 주실 수 있나요? (예시: 위로 올라가는 문은 자동문 마냥 열리는 것처럼) 이 통로에서 들어오고 문이 2개다보니깐 문이 계속 닫혀있는게 답답해보여서 열리면 어떨까 싶습니다.

**Comment by Hyoung-Seok** [comment]
이러면 콜라이더를 다시 싹 고쳐야 할 거 같아서 꼭 들어가야 하는게 아니면 다시 한번 검토할 필요가 있을것 같습니다.

**Comment by PZuHi** [comment]
앗 그러면 안 넣는걸로 합시당
