### ISSUE TITLE
[231106] 배경 오브젝트 상호작용 후 애니메이션 출력이 되나요?

### ISSUE THREAD

**Issue by PZuHi** [Team-Futurity/Futurity#264]
![image](https://github.com/Team-Futurity/Futurity/assets/100755257/bb6ab840-ed50-4488-8300-0752c7a7c750)
f 눌러서 홀로그램창 이미지가 열리면 애니메이션이 출력 되면 좋겠습니다. 전에 넣어둔 애니메이션이 사라졌는데 다시 넣어두면 되나요?

**Comment by Hyoung-Seok** [comment]
다시 넣어 놨습니다! 혹시 따로 만드신 2D 애니가 있는건 아니죠??

**Comment by PZuHi** [comment]
넹 따로 만든 2d애니메이션은 없습니다!

**Comment by Hyoung-Seok** [comment]
넵 그럼 이슈 Close처리 하겠습니다!
