### ISSUE TITLE
[231106] 몬스터 HP UI 변경

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#267]
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/4a0d2831-1565-4b6b-9c29-095d0cd01efe)

하얀색으로 표시한 두 몬스터의 HP 크기가 다릅니다.
빨간색으로 표시한 HP UI가 기본 몬스터들(엘리트X, 쫄몹X)에게 들어가는 HP UI이며
현재 원거리 몬스터에 적용 되어있는 UI가 엘리트 몬스터에게 적용되는 HP UI입니다. 
수정 부탁드립니다. 

더불어 쫄몹은 어떤 HP 프리팹을 사용 중인지 말씀 부탁드립니다.  
말씀해주신 위치에 UI 프리팹은 Normal과 elite 밖에 없어서 모르겠습니다........ 
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/b487c2c7-9c59-41fb-aec2-ea1526aa34d0)

**Comment by rbase0218** [comment]
지금 일반 몬스터는 Normal 데이터만 사용하고 있는게 맞습니다. 하단에 있는 몬스터가 RangedDefault가 맞나요?

![image](https://github.com/Team-Futurity/Futurity/assets/44202628/017a11e9-20ee-4cc7-b369-2fac4650077c)

위에 있는게 RangedDefault 몬스터에서 사용되고 있는 Sprite 사진입니다.

**Comment by KIMDODODODO** [comment]
보내주신 리소스 파일명을 봤을 때 하단에 몬스터는 RangedDefault가 아닌 것 같습니다.. 제가 확인할 방법이 있을까요?

**Comment by rbase0218** [comment]
늦었습니다. Enemy 프리팹에서 Normal Enemy HP Gauge 프리팹에서 수정해주시면 됩니다.
