### ISSUE TITLE
[231106] 스크립트 줄바꿈 미적용

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#268]
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/c43b99eb-d6f9-4f5c-af11-c9fc3c586855)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/678fca43-a543-4e77-90b3-d0a517839a02)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/77a54203-4258-4d1c-8489-569101529f14)

두 분 중에 스크립트를 작업하시는 분만 답변 부탁드립니다..
게임 전체에 줄 바꿈이 되어있지 않습니다.
스크립트에 줄 바꿈 부탁드립니다.

**Comment by Hyoung-Seok** [comment]
해당 사항 전달된 내용이므로 Close 처리 하겠습니다~
