### ISSUE TITLE
[231106] 튜토리얼 퀘스트 애니 누락

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#269]
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/139da574-32a2-4a5f-834b-c0dbb3abfffa)

튜토리얼 애니메이션이 적용되어있지 않습니다.
버튼 별로 애니메이션(y 버튼, x 버튼) 을 줬는데 혹시 튜토리얼 퀘스트(y+x 버튼) 마다 애니를 줘야 하나요?

![image](https://github.com/Team-Futurity/Futurity/assets/100762820/a3b76002-e653-4648-821d-d2b07b350444)
그리고 체크한 이미지의 위치를 살짝 바꿔야 할 것 같은데 바꿔도 될까요..? 문제 생길까요?

**Comment by rbase0218** [comment]
수정 완료했습니다. 이미지 위치 변경은 상관 없습니다!

**Comment by KIMDODODODO** [comment]
확인했습니다!

**Comment by KIMDODODODO** [comment]
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/d8b9e9e9-92b6-47ca-8a46-77fc22dd8ffc)

튜토리얼 프리팹 어디있는지 알 수 있을까요? 위치 변경 하려는데 어디에 있는지 몰라 여쭤봅니다..ㅜㅜ

**Comment by rbase0218** [comment]
튜토리얼 Perform은 프리팹이 따로 없습니다. Tutorial Scene에서 수정하시면 됩니다!
