### ISSUE TITLE
[231111] 송사리 스크립트 UI 이미지 이상함

### ISSUE THREAD

**Issue by MinjuGwak** [Team-Futurity/Futurity#301]
![image](https://github.com/Team-Futurity/Futurity/assets/89762274/31a85ab5-a08d-4dac-a501-97e42aeab984)

사리 이름이 나와야하는 위치에 눌린 사리가 들어가있습니다. 수정 부탁드립니다!

![image](https://github.com/Team-Futurity/Futurity/assets/89762274/483afcef-3e5e-4f32-adb5-ecb2bcd0f71d)

미래 이미지도 애니로 변경 부탁드립니다~

**Comment by rbase0218** [comment]
참조 이슈입니다. Dialog에서 어느 분이 수정하시거나, 이전 파일이 올라간 것 같습니다.
수정해두겠습니다.
