### ISSUE TITLE
[231111] UI 문제

### ISSUE THREAD

**Issue by KIMDODODODO** [Team-Futurity/Futurity#303]
**1. 크리티컬**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/34632c4f-bb1b-4993-96a1-2af5c70672d1)

- 크리티컬 이미지 크기가 너무 큽니다. 제가 유니티에 올린 사이즈로 부탁드립니다.
- 크리티컬이 몬스터 크기에 따라 다르게 뜨는데 이유가 있을까요? 없다면 동일한 크기로 부탁드립니다.

**2.튜토리얼**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/01688b72-4e1b-412b-8cbf-f9da5bc50409)

- XX 애니 적용이 안 되어 있습니다.

**3. 부품 선택 UI**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/67ad30bd-1bda-4992-9ba1-4045373dbe4e)

- 부품 이름 리소스로 변경 부탁드립니다. 해당 이미지는 테스트용으로 작업한 이미지 입니다.
- 뒤에 배경에 효과 적용 X (스토리보드 참고 부탁드립니다.)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/9d26d903-4271-4e90-ac2e-62e9af2f6ff5)
- 버튼 프리팹 적용 X
- 액티브 부품 위치 적용X

=> 제가 DEV 브랜치 프리팹 Part Canvas에 모두 수정했었습니다. 확인 부탁드립니다. 
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/614bffbd-d468-469c-8c86-7cf2ebe32242)

**4. 부품 장착 UI**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/844bc036-d307-4831-a0f2-38189219c876)

- 부품 이름 리소스 적용X
- 액티브 아이콘 적용 X
- 액티브 쪽에 네모 상자는 어둡게 표시하려고 잡아두신 건가요? 리소스 자체를 어둡게 하는 게 무리일까요?

**5. Player info 액티브 100% 시 이펙트**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/37cc0990-3fee-45d5-8d59-a4e04a7914c8)

- 액티브 100% 시 UI 이펙트 적용 X, 적용 부탁드립니다. 

**6.몬스터 HP**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/6f882729-2cfa-4144-b7f3-c3f36880ff17)

- 둘이 HP 크기가 다릅니다. DL-F 몬스터의 HP가 엘리트 몬스터 HP입니다. 

**7. 로딩 화면 UI **
https://github.com/Team-Futurity/Futurity/assets/100762820/194180f9-3bb6-4bf3-8746-4cc84136b324
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/7830bc34-2949-4972-bdca-9059d533e57a)

- 오토바이 탄 미래가 사라지는 연출 적용 X, 체크한 흰색 부분 뒤로 들어가야 합니다. (Front Frame Image)
스토리보드 참고 부탁드립니다.
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/bb6a47c2-fadd-4202-81ec-8f4d414f12f9)

**8. 일시 정지**
- 저희 일시 정지 안 들어가나요?

**9. 크레딧**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/7edc297e-2d91-488b-ba24-9775d27e22a6)

- 텍스트, 간격, 색 적용 X
=> 제가 W 1920, 세로로 길게 작업해서 유니티에 올려두고 디코에 언급하겠습니다. 이걸로 적용 부탁드립니다.
- 시간이 너무 빠릅니다. 시간 조금 더 길게 부탁드립니다.

== > 작업하실 때, 스토리보드 꼭 읽어주셔야합니다. 제가 생각한 UI 연출과 예시 문서가 적혀있으니 꼭 읽어주세요. 

**10. 스탠딩 스크립트**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/a9db6440-8957-41e7-9ef5-2c60c1d81ea6)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/9ea11150-de4c-40ea-9824-c9c9b297c0f7)

- 주희씨가 말씀 해주신 스탠딩 연출 방법인데 작업 가능하실까요?

**11. A로 넘어가기, A로 상자열기 위치**
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/695ae079-d901-4e9b-98a2-d4dc99e2b26d)

- 크기가 너무 작아 수정해야 할 것 같은데 유니티 내 어디에 있나요?

**Comment by Hyoung-Seok** [comment]
10 - 스탠딩 스크립트의 경우 적용 시 미래가 마감 직전 3일간 밤 샌 프로그래머처럼 나와 뺐습니다. 이는 주희님께 전달드린 내용입니다.
![image](https://github.com/Team-Futurity/Futurity/assets/72616031/e825b746-052a-4113-b2fb-08bd24022e25)

**Comment by Hyoung-Seok** [comment]
11 - 해당 UI의 경우 Asset > 02Prefab > 07Map > ChapterMoveController 프리팹 하위에 존재합니다!

**Comment by KIMDODODODO** [comment]
두 문제 다 확인했습니다!  ChapterMoveController 프리팹은 크기만 수정 진행하도록 하겠습니다~ 감사합니다~!!

**Comment by rbase0218** [comment]
1. 크리티컬 이미지는 World Canvas에서 진행되고 있어서 실제 리소스 크기와 맞추기가 어렵습니다.
     그렇기 때문에 이전에 은우님이 올려주신 Issues#290을 참고해주시면 감사하겠습니다.

2. 확인하겠습니다.

3. 부품 관련된 리소스는 전부 데이터로 빼낸 것으로 기억하고 있는데 확인 후에 다시 작성해두겠습니다.
    또, 뒤에 배경은 이전에 프리팹에 Sprite Renderer가 제거된 것 같습니다. 확인하고 변경하신 것 참고해서 수정하겠습니다.

4. 어둡게 표시하려고 잡아둔게 맞습니다. 리소스 자체를 어둡게 처리해두겠습니다.

5. 이펙트는 참조 풀린 것 같습니다. 이는 확인이 종료된 사항이라 넘어가겠습니다.

6. 확인하겠습니다.

7. 동영상 액세스 권한 허가 부탁드립니다. 사라지는 연출 적용 X라고 하셨는데, 검은 프레임 너머로 이동하면 사라지는게 아닌가요??

8. 일시정지 개발 완료된 상태입니다. 키 바인딩 참조가 풀린 듯 합니다.

9. 텍스트 변경 확인했습니다. 시간이 빠른건 유니티 인스펙터에서 기획측에서 속도 조정이 진행되어야 합니다.

**Comment by KIMDODODODO** [comment]
1번의 경우 이슈를 확인 후, 제가 유니티 내에서 수정 완료했습니다.
이건 궁금해서 여쭤보는 질문인데 몬스터 크기에 따라 크리티컬 크기가 다르게 뜨는 것 또한 World Canvas의 문제인 건가요??

7번의 경우 사라지는 연출이 적용되어 있지 않다는 말씀을 드리려고 축약해서 말씀드린 부분이었습니다. 전달에 혼란을 드려 죄송합니다. 검은 프레임 너머로 이동하며 사라지는 게 맞으며 해당 영상을 같이 전달해 드립니다. 전체 화면으로 녹화를 진행했던지라 하단에 오토바이 탄 미래 리소스만 확인해 주시면 될 것 같습니다. 

https://github.com/Team-Futurity/Futurity/assets/100762820/1c4685c1-333c-4488-a9a2-382f68afda6f

9번은 제가 기획자와 추가로 이야기 후 속도 조정을 진행하도록 하겠습니다.

긴 글에 답변해 주셔서 감사합니다~!!

**Comment by rbase0218** [comment]
몬스터 크기에 따라 크리티컬 크기가 다르게 나오는 점은 확인해봐야 할 것 같습니다. 이전에 #290 이슈에 따라서 제가 각각 크기를 Width * 0.1 / Height * 0.1로 맞춰놨었는데, 이미지 크기가 다르다면 봐야할 것 같습니다. 만약에 동일하다면 World Canvas 사유로 보입니다.

7번의 경우에는 방금 확인을 해봤는데 제 브랜치에서는 확인이 되고 있는데, 혹시 어떤 상황에서 발생하는지 알 수 있을까요?

**Comment by KIMDODODODO** [comment]
크리티컬이 몬스터 크기에 따라 다르게 나오는 건 한 번 확인 후 연락 부탁드립니다. World Canvas의 사유로 몬스터 크기에 따라 리소스가 크기가 다르게 나온다면 현재 상황을 유지한 채 크리티컬 문제는 끝내도록 하겠습니다.

7번의 경우 어떤 상황에서 미래가 프레임 너머로 사라지는지에 대해 여쭤보시는 게 맞으실까요? 오토바이 탄 미래 리소스(이미지 내 노란색)가 오른쪽 화면 끝으로 올 때 생기는 상황에서 발생하는 연출입니다.

![image](https://github.com/Team-Futurity/Futurity/assets/100762820/c8daff31-556e-45b1-b7fa-f7ccb5ab94d5)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/c690b08c-ccad-4dff-a64c-05d32ab7fef3)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/f294105e-7219-4ef5-8ccf-5d2dad68d917)
![image](https://github.com/Team-Futurity/Futurity/assets/100762820/40b75b57-b1e6-41b6-99b1-0f9003fc5ba9)


현재 빌드 파일에서는 미래가 프레임 너머로 안 사라지는데
https://github.com/Team-Futurity/Futurity/assets/100762820/c16f3330-347e-4194-816c-761dfe1987b2

제가 스토리보드에 적은 로딩화면 연출은 미래가 (노란색) 프레임 너머(흰색)로 사라지는 연출입니다.
https://github.com/Team-Futurity/Futurity/assets/100762820/1de16fcd-6e4b-48ce-80b9-d66f59440f7e

**Comment by rbase0218** [comment]
1. 사이즈가 전부 다 동일합니다. World Canvas에서 보이는 차이 혹은 카메라에 의해서 사이즈가 달리 보이는 것 같습니다.
   크리티컬 이미지가 너무 큰 것은 Critical Canvas의 Critical Image를 통해서 조절해주시면 감사하겠습니다.

2. 애니메이션 누락 확인 후, 추가했습니다.

3. Part Canvas 그대로 적용되도록 수정했습니다. 액티브 부품 위치 적용이 안되었다고 하셨는데, 무슨 뜻인지 풀어주시면 감사하겠습니다.

변경된 Active 데이터는 위치 퍼블리싱 완료한 바 있습니다.
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/64f9f134-5d7b-4451-9512-129b0e4eb648)

4. 부품 이름 리소스 적용이 안되었다는 말이 어떤 것인가요? 저 상태에서 리소스가 보이지 않는 것을 말하시는 것이라면 RewardBox를 통해서 Window를 여셔야합니다.

5. 이펙트 누락은 이전 작업 시에 형석님과 작업이 겹치면서 생긴 이슈입니다. 수정했습니다.

6. 몬스터 이슈는 이전부터 말씀드렸었는데, 둘 다 같은 리소스를 공유하고 있습니다. 

- D_BF
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/07088ef0-7530-4e4c-aebf-1f81ae00db1d)
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/476948a6-1843-4441-8797-c70cafc33a03)
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/274d49c4-43e9-4dac-a1dc-1d6778f6513c)
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/e09e5a37-9894-4d9c-aeca-54e1367caca4)

- MeleeDefault
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/e78cecc0-fef1-41ec-867c-8eeaa5bc6068)
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/8d7163b6-4ae9-4432-b8d6-3ba4d72077dc)
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/774ee441-5256-49f5-bc61-cf9715f9bab4)
![image](https://github.com/Team-Futurity/Futurity/assets/44202628/61af353f-6f9f-4c7a-bcdb-ec873c13b313)

Assets -> 02Prefab -> 01Enemy -> D_BF
Assets -> 02Prefab -> 01Enemy -> MeleeDefault

그래도 제가 놓치는 것일 수 있으니, 각각 경로에 존재하는 프리팹의 'Normal Enemy HP Gauge Canvas'의 하위 오브젝트 리소스 확인 요청드립니다.

7. Order 수정해서 Front Frame이 앞으로 가게 수정했습니다.

8. 기존에는 UI Behaviour Map에서만 작동하는 것을 확인했고, Player Map에서도 추가 했습니다.

**Comment by KIMDODODODO** [comment]
1번 크리티컬의 경우 지속적으로 확인하며 제가 크기 수정하도록 하겠습니다.

3번 부품 선택 화면의 경우 UI가 액티브 / 패시브에서 액티브 + 패시브로 바뀌며 선택지가 패시브-패시브-패시브 에서 액티브-패시브-패시브로 바뀌었습니다. 11월 11일 빌드 파일 내에서 패시브-패시브-패시브로 선택지가 보여 액티브 부품 위치 미적용으로 이슈를 올렸습니다.
수정이 완료되었다면 문제는 없을 것 같습니다.
그리고 배경 효과 적용 부탁드립니다. (블러+어두운 효과)

4번의 경우 11월 11일 빌드 파일 내 부품 선택 UI화면의 부품 이름 리소스가 알파 아이콘 - 알파 이름 리소스로 뜨는게 아니라 모두 감마 이름 리소스로 떠서 말씀드린 부분입니다. 
이 부분은 부품 선택 화면 UI의 기능이 모두 작업 완료된다면 수정되는 부분일까요?

6번의 경우 저도 한 번 더 체크를 해보도록 하겠습니다. 

이 외의 부분은 확인했습니다. 감사합니다.
