### ISSUE TITLE
[231113] 알파 베타 궁극기 씬 이펙트가 움직이지 않는 문제

### ISSUE THREAD

**Issue by MinjuGwak** [Team-Futurity/Futurity#341]
![image](https://github.com/Team-Futurity/Futurity/assets/89762274/666a7433-cd8a-41db-88cb-c43549f7e155)
![image](https://github.com/Team-Futurity/Futurity/assets/89762274/aae72861-4f69-4eb8-95d2-5e2b170ac483)
원래 빙글빙글 돌아가야 합니다... 게임 씬에선 잘 움직이는데 빌드만 확인해보면 계속 이펙트가 멈춰있네요...

**Comment by Budy123** [comment]
최신 빌드에서 수정되었습니다.
