### ISSUE TITLE
[231115] 튜토리얼이 끝나고 1스테이지로 갈때 일시정지 화면

### ISSUE THREAD

**Issue by silvereun36** [Team-Futurity/Futurity#360]
튜토리얼이 끝나고 1스테이지로 갈때 일시정지 화면이 떠서 게임을 플레이 할 수 없습니다.
![image](https://github.com/Team-Futurity/Futurity/assets/64335656/0ad704e1-dfd5-4d36-a82b-7159ecc9709b)

**Comment by Hyoung-Seok** [comment]
픽스 완료
