### ISSUE TITLE
1-2 스테이지 클리어 연출 이슈

### ISSUE THREAD

**Issue by Koheunwoo** [Team-Futurity/Futurity#362]
![image](https://github.com/Team-Futurity/Futurity/assets/112710152/46b2f9d9-996d-42e9-81b6-ecda40bec99b)

1-2 스테이지에서 모든 몬스터가 사망하여도 스테이지 클리어 연출이 출력되지 않습니다.

상세
- 마지막 몬스터 사망 연출이 출력되지 않음
- 위치 안내 화살표가 출력되지 않음
- 보상 상자가 열리지 않음
- 다음 스테이지로 넘어가지 못함

**Comment by Hyoung-Seok** [comment]
픽스 했습니다!
